### ISSUE TITLE
How about implementing functionality for multidimensional time series?

### ISSUE THREAD

**Issue by deneal123** [NX-AI/flashrnn#1]

**Comment by kpoeppel** [comment]
You can always use multiple dimensions as they will have to be projected (outside of flashrrn) to the hidden dimension size anyways. The formulas typically look like:
`g = W x + R y + b`
but in FlashRNN the ` W x ` part is externalized, the `flashrnn` function takes the result of this linear layer. Given you have a multi-dimensional timeseries, just extend our external projection matrix W to match the dimensions.

If that's not what you meant, please clarify!
